name: Kernel-Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch of kernel source'
        required: true
      tc:
        description: 'Toolchain'
        required: true

env:
  BRANCH: ${{ github.event.inputs.branch }}
  TC: ${{ github.event.inputs.tc }}
  TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest
    container:
          image: renayura/archlinux:latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Build
         run: |
              pacman -Syu --needed --noconfirm inetutils bc cpio git
              git clone --depth=1 https://github.com/Alvinaja/kernel_xiaomi_mt6768 -b $BRANCH kernel
              cd kernel
              wget https://raw.githubusercontent.com/Renayura/Scripts/master/kernel-build.sh
              bash kernel-build.sh $TC
